### ISSUE TITLE
NRP (AEP) Service Color Scheme Needs Update

### ISSUE THREAD

**Issue by derekgiardino** [NOAA-OWP/hydrovis#1009]
The AEP (NRP) FIM color scheme matches too close to categorical FIM, so we need to adjust this service [NWP AEP](https://maps.water.noaa.gov/server/rest/services/fim_libs/static_nwm_aep_inundation_extent_library_noaa/MapServer) so that the legend looks more like the exceedence legend from the high flow magnitude FIM. ![Image](https://github.com/user-attachments/assets/77e5f249-ad3c-4a2a-9daf-abc160501e78)

**Comment by LorneLeonard-NOAA** [comment]
No data loading ATM with both Feature Server and Map Server. Logged in with my NOAA account.

![image](https://github.com/user-attachments/assets/4a2808bc-3def-4fc5-9dd2-48bbad517747)

**Comment by LorneLeonard-NOAA** [comment]
Color Values

**2%**
FF00E5
**4%**
9E00FF
**10%**
1400FF
**20%**
2EC6FF
**50%**
39EFFF
**> 50%**
B4FFF2

**Comment by GeorgeRought-NOAA** [comment]
![Image](https://github.com/user-attachments/assets/26e9ea4a-3ecf-4fa2-9281-d69b61ae3e86)

- Edison, Katherine and Shawn walked Lorne and I through troubleshooting database connection issues with static_nwm_aep_inundation_extent_library_noaa.mapx

- AEM FIM colorized to match the high flow magnitude FIM. 

- .mapx created

**Comment by derekgiardino** [comment]
THanks and great work guys, i am going to run this image to a few to ensure this meets expectations.

**Comment by derekgiardino** [comment]
Currently all the feedback I received was immensly positive (nice work again), the only suggestion was seeing if there was any way to create a larger differentiation between the 20 and 50% values so that it still fit in the color scheme, but could tell the distinction a little clearer.  Didn't know if it could be done but thought I would throw the challenge your direction.  If not, no worries we will likely push this to TI and get this into our next build.

**Comment by derekgiardino** [comment]
Also a side quest, the legend still calls these values AEP but should be NRP, can that be switched in the mapx file to fix the legend?

**Comment by GeorgeRought-NOAA** [comment]
Thanks, Derek! No problem. We can change both of those things. I'll post an updated image in here with a new color option.

**Comment by GeorgeRought-NOAA** [comment]
2% NRP Feature ID 24601735 is the feature in the example image for reference. 

Legend Layer Names changed from AEP to NRP

20% Layer color hexcode changed from 2EC6FF to 2D9FFF for increased contrast.

New .mapx file created.

![Image](https://github.com/user-attachments/assets/af93cad2-ce91-4dd5-9659-7f0577e1e28b)

**Comment by derekgiardino** [comment]
George this is great.  I think we are there with this.  Lets get this PR merged and moved to TI.  Please reach out to Katherine or Shawn for assistance with that
