### ISSUE TITLE
Restructure directory structure

### ISSUE THREAD

**Issue by CoreyKrewson-NOAA** [NOAA-OWP/hydrovis#219]
Update the repo directory structure to be based on application, not on AWS service

**Comment by CoreyKrewson-NOAA** [comment]
@nickchadwick-noaa Is this still something that we want to do? Or do we just leave it how it is currently?

**Comment by nickchadwick-noaa** [comment]
I'm going to do a rough outline of this to see if it'll work well for our stack.
