### ISSUE TITLE
NWM Short-Range Forecast Water Management

### ISSUE THREAD

**Issue by CoreyKrewson-NOAA** [NOAA-OWP/hydrovis#239]

**Comment by cfitzpat479** [comment]
I've checked the old viz loosa folder to see how this service was developed. Unfortunately, it doesn't seem to be working on on-prem production, so I cannot view the attributes. In other words, it's unclear what I'm supposed to recreate.

**Comment by cfitzpat479** [comment]
I found the old on-prem file: https://vlab.noaa.gov/redmine/projects/owp_gid-data-visualization/repository/owp-viz-services/revisions/production-3.0/entry/loosa/products/reservoir.py

after looking through the old paths.py file (https://vlab.noaa.gov/redmine/projects/owp_gid-data-visualization/repository/owp-viz-services/revisions/production-3.0/entry/loosa/consts/paths.py), I realized the service is pulling from a derived dataset that has not been recreated in HydroVIS yet. I don't know yet where to find the v3 static reservoir file. Shawn is assisting me on this quest!
