### ISSUE TITLE
Create Waterbody Reference Services for HI and PR/VI

### ISSUE THREAD

**Issue by MonicaStone-NOAA** [NOAA-OWP/hydrovis#315]
Create waterbody reference services for the Hawaii and Puerto Rico/U.S. Virgin Islands NWM domains.  Currently, only a ConUS version exists.

**Comment by CoreyKrewson-NOAA** [comment]
@MonicaStone-NOAA The current prod service has waterbodies for Puerto Rico. It should also have Hawaii but I am not seeing any. Are there just no NWM waterbodies there?

https://maps.water.noaa.gov/server/rest/services/reference/nwm_waterbodies/MapServer

**Comment by MonicaStone-NOAA** [comment]
@CoreyKrewson-NOAA Oh I did not know that, but I see it now.  And actually, I do see a couple in Hawaii too.  So that existing service must have all waterbodies.  Since we have separate services for the flowlines, I just assumed that we didn't have waterbodies published for HI and PR/VI.  Do you think we should keep them all in the same service, or break them up into different services like we do for the flowlines?

**Comment by CoreyKrewson-NOAA** [comment]
To keep consistency with the flowlines, it might be good to split them up

**Comment by MonicaStone-NOAA** [comment]
@CoreyKrewson-NOAA Are these services on UAT now?

**Comment by CoreyKrewson-NOAA** [comment]
They are still in TI/dev
