### ISSUE TITLE
Add Timestamp Attributes for Services with Attributes Reported in Hours

### ISSUE THREAD

**Issue by MonicaStone-NOAA** [NOAA-OWP/hydrovis#316]
Many of the services that depict timing information on high flow conditions, contain attributes with times reported in hours.  Add complimentary attributes to each of these that tell the user the specific time.  For example, instead of just reporting high water arrival time to be forecast for 72 hours from the reference time, add an attribute that indicates this will be on 2/17/2023 @ 12z (the format of the timestamp should match the format used by other timestamp attributes).

**Comment by CoreyKrewson-NOAA** [comment]
Here are some steps we need to take to get this done:

- [ ] Test SQL to figure out a new datetime from a starting time (reference time for example) and hour value (time to peak for example)
- [ ] Apply previous SQL to timing fields
- [ ] Update pro projects to use new fields types and lengths as necessary

**Comment by shawncrawley** [comment]
![Image](https://github.com/NOAA-OWP/hydrovis/assets/12499203/61ee23b9-c3d9-4d30-bd1c-6fbd56cb8a6d)

@CoreyKrewson-NOAA , @TylerSchrag-NOAA How does this logic look? I just adapted from this: https://stackoverflow.com/questions/5266758/dynamic-column-based-interval

**Comment by CoreyKrewson-NOAA** [comment]
This looks great! I like it a lot. We are planning to do this for all timing services correct?

**Comment by shawncrawley** [comment]
Correct. I just wanted to run that logic by you guys before I apply it everywhere.

**Comment by CoreyKrewson-NOAA** [comment]
yeah, looks good to me

**Comment by shawncrawley** [comment]
@MonicaStone-NOAA I have an important question with regard to implementing this. Is it worth renaming some of the existing fields as I add these new date-time-string oriented fields? For example, the "peak_flow_arrival_time" services have current fields with names `peak_flow_arrival_hour` and `below_bank_return_time`. Both fields are storing the hours, while only one of them explicitly uses "hour" in the name. Ideally, we could rename `below_bank_return_time` to `below_bank_return_hour`, and then I can have both new fields named `peak_flow_arrival_time` and `below_bank_return_time`. Will that require too much reconfiguration? The alternative is of course to just come up with completely new and unique names for the fields so we're only adding new fields and not changing any existing. What's your verdict?

**Comment by MonicaStone-NOAA** [comment]
The new names as you propose them sound ideal to me.  It will require some reconfiguration on WPOD's end, but it's not too hard a lift and I think it will be worth it.

**Comment by TylerSchrag-NOAA** [comment]
This is not an important comment, but I'm excited about this enhancement! Can't wait to see what you all do with the time-enabled functionality on the ArcGIS side (time sliders, animations, etc.).
