### ISSUE TITLE
Create an NWM 48-Hr Rapid Onset Flooding Forecast Service for HI

### ISSUE THREAD

**Issue by MonicaStone-NOAA** [NOAA-OWP/hydrovis#317]
Create an NWM 48-Hour Rapid Onset Flooding Forecast service for Hawaii.

**Comment by CoreyKrewson-NOAA** [comment]
Here are some steps we need to take to get this done:

- [ ] Create a new product config for this service
- [ ] Create a new postprocess sql file for this service (it may be possible to copy the existing versions and update tables as necessary to point to new domains or NWM configurations)
- [ ] Create a new summary sql file for this service (it may be possible to copy the existing versions and update tables as necessary to point to new domains or NWM configurations)
- [ ] Create a new pro project for this service
