### ISSUE TITLE
Retrofit RnR Model for AWS Development

### ISSUE THREAD

**Issue by TylerSchrag-NOAA** [NOAA-OWP/hydrovis#339]
At present, updates to the RnR model are cumbersome due to Chip's development environment limitations and his work on other projects... and at some point, we need to bring the development of RnR fully into AWS.

At the very least, this means orienting one or two other developers with a tutorial on how to edit and update the model on the RnR EC2 instance in AWS. Ideally, we could containerize the model in ECS... including some refactor to abstract out key input arguments, so that we can integrate it seamlessly with our Viz Step Function pipelines.

**Comment by CoreyKrewson-NOAA** [comment]
so close
