### ISSUE TITLE
Harden current workflow for historical runs

### ISSUE THREAD

**Issue by CoreyKrewson-NOAA** [NOAA-OWP/hydrovis#350]
I know we have a lot of this hashed out but with FIM4 now being available, we will have to start recreating a lot of data for workshops, trainings, papers, etc. Let's get an example reference time, location, and service and get the workflow documented and hardened. Lets add the workflow to the milestone description and/or the hydrovis guide so that anyone will be able to follow the workflow

Sub-tasks (related to FIM 10% Data Requests - End of April 2023 #424)

- [x] Test current pipelines with past events, fix any bugs to make sure the logic still works
- [x] Start processing immediate training data requests
- [x] Coordinate with Chip on RnR runs
- [ ] Reconcile all historic fixes in feature branch / PR
- [ ] Run EC2 pipelines / integrate EC2 pipelines with step functions.

**Comment by TylerSchrag-NOAA** [comment]
I'm going to close this issue, and just track progress in #424
