### ISSUE TITLE
Replace and Route - Inherited RFC forecasts attribute includes no_flooding gage

### ISSUE THREAD

**Issue by CoreyKrewson-NOAA** [NOAA-OWP/hydrovis#390]
Refer to this ticket for more information https://vlab.noaa.gov/redmine/issues/113359

Maybe this is actually supposed to be occurring but I assumed we wouldn't even be querying no flooding gage flows and therefore a no_flooding gage streamflow wouldn't be used in the model. Is this even an issue?

**Comment by shawncrawley** [comment]
Replace and Route has been redesigned and redeployed since the creation of this issue. It is likely that this issue is now resolved in the newer version, so we'll go ahead and close this ticket. A new one will naturally be created if the issue resurfaces with the new version.
