### ISSUE TITLE
CIDR updates and restructuring

### ISSUE THREAD

**Issue by CoreyKrewson-NOAA** [NOAA-OWP/hydrovis#393]

**Comment by CoreyKrewson-NOAA** [comment]
Waiting on NWPS setting up staging and prod

**Comment by nickchadwick-noaa** [comment]
This will be done automatically with the rollout of the DR setup scheduled for V2.1.1.

**Comment by CoreyKrewson-NOAA** [comment]
Will be taken care of with #467
