### ISSUE TITLE
RFC Ingest Unit Issues

### ISSUE THREAD

**Issue by CoreyKrewson-NOAA** [NOAA-OWP/hydrovis#419]
See this ticket for more information. https://vlab.noaa.gov/redmine/issues/115393. Basically the issue here is that for 4/21 @ 12Z there was an example of a unit conversion bug. The forecast ingested into RnR was in CFS. The WRF-Hydro output were the same exact value but in CMS. When we put the data into the DB, we converted it into CFS which multiplied the actual value by 35.

There seems to have been some bug with the forecast being ingested into WRF-Hydro and a units issue.

**Comment by CoreyKrewson-NOAA** [comment]
@shawncrawley think this is resolved with your new implementation?

**Comment by shawncrawley** [comment]
Yes, I believe so. I was very thorough in making sure I got units correctly. If there are issues remaining then I'd wager they are coming from the WRDS databases that I query.

**Comment by shawncrawley** [comment]
Replace and Route has been redesigned and redeployed since the creation of this issue. It is likely that this issue is now resolved in the newer version, so we'll go ahead and close this ticket. A new one will naturally be created if the issue resurfaces with the new version.
