### ISSUE TITLE
FIM Historical Events Requests

### ISSUE THREAD

**Issue by TylerSchrag-NOAA** [NOAA-OWP/hydrovis#424]
25 historical events requested by field.

- [x] Figure out RnR model run strategy
- [x] Figure our geopackage production strategy (in alignment with data archival plan)
- [x] Figure out where to run (I think TI will work?)
- [x] Confirm ETA with Derek
- [x] Produce and test first event
- [x] Conveyer belt the rest
- [x] Reconcile changes back into PR

**Comment by TylerSchrag-NOAA** [comment]
Update for documentation: All but David Vallee's requests were finished in late May/June 2023. Of those requests, I sent the data I was able to generate before the Great TI Purge of '23 to Catherine F in late July, and am trying to set the pipelines back up to finish the rest now.

**Comment by CoreyKrewson-NOAA** [comment]
We have completed the work on our end and awaiting feedback
