### ISSUE TITLE
Calculate CONUS AEP statistics for NWM 3.0

### ISSUE THREAD

**Issue by CoreyKrewson-NOAA** [NOAA-OWP/hydrovis#469]
- [x] Edit Python script used to calculate streamflow AEPs to be ready for NWM v3
- [x] Test Python script on PRVI annual max flow summary file
- [x] Receive and review the annual max flows summary file
- [x] Conduct descriptive statistics on CONUS max flow summary file
- [x] Conduct statistical comparison of NWM v2.1 and NWM v3 annual max flow summary files
- [x] Calculate new Streamflow AEPs using the NWM v3 annual max flows 
- [x] Conduct statistical comparison of NWM v2.1 and NWM v3 Streamflow AEP files
- [x] Conduct spatial analyses of NWM v3 Streamflow AEPs using Test Data from NWM v2.1 analysis
- [x] Make changes and re-calculate NWM v3 Streamflow AEPs as needed
- [x] Generate visuals (maps, charts) and create slides of new Streamflow AEPs and High Water calculations for NWC leadership and

**Comment by KatherinePowell-NOAA** [comment]
Working on the maps and visuals and staying in contact with WPOD and GID.
