### ISSUE TITLE
Calculate Alaska AEP statistics for NWM 3.0

### ISSUE THREAD

**Issue by CoreyKrewson-NOAA** [NOAA-OWP/hydrovis#470]
- [x] Edit Python script used to calculate streamflow AEPs to be ready for NWM v3 Alaska domain
- [x] Test Python script on "generated" max flow summary file - Alaska domain
- [x] Receive and review the Alaska annual max flows summary file
- [x] Conduct descriptive statistics on Alaska max flow summary file
- [x] Calculate new Streamflow AEPs using the NWM v3 annual max flows - Alaska domain
- [x] Conduct spatial analyses of NWM v3 Streamflow AEPs - Alaska domain
- [x] Make changes and re-calculate NWM v3 Streamflow AEPs as needed

**Comment by KatherinePowell-NOAA** [comment]
@KatherinePowell-NOAA will be receiving the max flows file from NCAR approx Aug 31-Sept 8th
