### ISSUE TITLE
Get event notifications configured for "para" folder of shared NWM bucket

### ISSUE THREAD

**Issue by shawncrawley** [NOAA-OWP/hydrovis#491]
The NWM v3.0 "para" files are currently depended upon by the various configurations of Coastal FIM services - specifically relying on the new coastal total_water NWM outputs. We are currently relying upon [PARA NOMADS](https://para.nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/para) to retrieve and process those files. However, they have been very inconsistent, either not showing up at all or with unpredictable delays. Due to this unreliability, we cannot yet foster a much needed QA/QC and testing of these services in UAT.

I spoke with @TylerSchrag-NOAA today, and confirmed that 1) the "para" folder exists and is being pushed to on the shared NWM bucket and 2) it wouldn't be too difficult on our end to accomodate the "para" notifications if the existing event notifications on that bucket were modified to remove "/prod". This, of course, would require an update to our code in all three environment (i.e. TI/UAT/PROD) to ensure that we capture and process the new notifications appropriately - effectively ignoring any from para except those for the total_water files.

Does this sound like a good approach?

**Comment by CoreyKrewson-NOAA** [comment]
This was completed
