### ISSUE TITLE
Create FIM Service Implementation static service map

### ISSUE THREAD

**Issue by KatherinePowell-NOAA** [NOAA-OWP/hydrovis#503]
![Image](https://github.com/NOAA-OWP/hydrovis/assets/76983310/5053fcb9-db84-45db-a876-f990e72969c1)

**Comment by KatherinePowell-NOAA** [comment]
I think Tyler did this? I'll check

**Comment by TylerSchrag-NOAA** [comment]
I do have an outstanding task of updating the database feature classes to reflect the most current public release domains... I'll do that. We should talk about the map service part of this though - it may be better for that to live in NOAA Geoplatform... and I'm pretty sure Lauren already created that when she last updated the map.
