### ISSUE TITLE
Troubleshoot missing RnR sites

### ISSUE THREAD

**Issue by shawncrawley** [NOAA-OWP/hydrovis#594]
From @CarsonPruitt-NOAA:

> IDK if you all are aware of this yet or not, but the R&R isn't being produced for several forecast points in the PNW (and thereby no RFC FIM). The upper-most LID in the screenshot below is NEWW1.

![Image](https://github.com/NOAA-OWP/hydrovis/assets/12499203/ed6d5ffb-d501-453f-bd3c-3c6d45c6ef26)

**Comment by shawncrawley** [comment]
From @cfitzpat479 via the NWS/OWP HydroVIS Project Google Chat Space :

> and no pressure, but Western RFC is visiting the NWC this week and we were planning on doing a live event FIM scenario in the PNW this afternoon

**Comment by shawncrawley** [comment]
I found the issue - and it's very important to point out and understand. The latest (at the time of typing this) forecast at `NEWW1` (captured below) does not reach its action threshold until midday on December 5.

![Image](https://github.com/NOAA-OWP/hydrovis/assets/12499203/8d84d743-527d-41ee-81b1-4d891a0b26d5)

The RnR services are 5-day forecast services, looking out exactly 5 days (i.e. 120 hours) to the hour from the latest available AnA forecast. At the time of writing this, the latest AnA forecast is `2023-11-29 16:00:00 UTC`, with 5 days out from that being `2023-12-04 16:00:00 UTC`. In that time frame, a threshold of action or greater is never reached.

This has come up before, and we obviously have yet to adequately solve this problem. One side to the debate is that we should keep our implementation as is - since it's accurately depicting what the service sets out to depict (i.e. RnR modeled at and downstream of sites that exceed action or greater threshold during the 5 day forecast window from the latest AnA reference time). The other side to the debate is that we should maybe still show the underlying RnR FIM map (even though the extent would not represent action or greater flooding since in this case action or greater is not actually modeled), but have some sort of attribute that indicates that there is a discrepancy between the max status of the RFC Max Forecast service and that of the underlying RnR model (and thus FIM).

Any thoughts would be appreciated.

**Comment by CarsonPruitt-NOAA** [comment]
Thanks for looking into this Shawn. I understand now why there's not RFC FIM being produced for these gages. Can you also look into another gage `tolw1` and `squw1`. These are a bit different, so it may be better to track in a different issue, but these are RFC forecast points that are not showing up in the AHPS Max Stage service and are also not being included in the Replace and Route domain. Here's a shot of the current hydrograph for `tolw1`.
![image](https://github.com/NOAA-OWP/hydrovis/assets/90792257/b56dd4f8-0a80-4389-9d92-f428cd2dece4)

**Comment by shawncrawley** [comment]
@CarsonPruitt-NOAA, I am digging into this now. I'll let you know what I find.

**Comment by shawncrawley** [comment]
After some digging, I found two things. 

First, those two points you mentioned do not show up in the "RFC Max Forecast" service because this service depends specifically upon the "stage" forecasts as provided by the WRDS API, and the stage thresholds are not defined for those sites. I wondered if that was a WRDS API shortcoming, but that seems consistent with what I see on each site's official AHPS page. Back to the WRDS API, if you compare the "stage" WRDS Forecast API with the "streamflow" endpoint, only the "streamflow" results have the stage thresholds defined and are thus able to correctly assign each forecast point a flood status. Verify here:

https://nwcal-wrds.nwc.nws.noaa.gov/api/rfc_forecast/v2.0/forecast/stage/nws_lid/TOLW1/  VS  https://nwcal-wrds.nwc.nws.noaa.gov/api/rfc_forecast/v2.0/forecast/streamflow/nws_lid/TOLW1/ 

https://nwcal-wrds.nwc.nws.noaa.gov/api/rfc_forecast/v2.0/forecast/stage/nws_lid/SQUW1/  VS  https://nwcal-wrds.nwc.nws.noaa.gov/api/rfc_forecast/v2.0/forecast/streamflow/nws_lid/SQUW1/

I believe there has been fairly recent talk of incorporating "streamflow" forecasts into the RFC Max Stage service as well. I'll have to circle back to my team for an update on that. It sounds like that's the way we'd need to go.

The other thing I discovered - and this one relates to those sites being missing from the Replace and Route domain - is that those sites should still definitely be showing up in the RnR services, since this service was built to consider both stage and streamflow forecasts. So the reason those aren't being reflected there is actually due to a small bug that I found and am able to fix very easily. I will get permission to apply this hotfix as soon as possible.

Thanks again for reporting these issues!

**Comment by CarsonPruitt-NOAA** [comment]
That's what I was expecting. Their flood thresholds are based off flows instead of stages. 
![image](https://github.com/NOAA-OWP/hydrovis/assets/90792257/fdc2470f-8714-42f7-921d-c61b1932384d)

I think we should definitely circle back around on this because there are several RFC forecast points in the western portion of the 30% that are similar. If we don't add the ability to ingest these thresholds, R&R/RFC FIM won't be produced for any of these gages when that area goes public next year. You don't need to look into these, but I want to include them here as a record:
```
TOLW1
SQUW1
NISW1
ORTW1
MAYW1
SMRW1
ISSW1
WRAW1
AUBW1
SPEW1
MAYW1
```
Adding @derekgiardino for awareness

**Comment by shawncrawley** [comment]
Yeah, I don't think it would be too difficult to incorporate the streamflow-based forecasts. Also, I just pushed the simple hotfix to the RnR services. You can go ahead and verify that those are now showing up on your end.

**Comment by CarsonPruitt-NOAA** [comment]
No way, that's awesome! Thank you for pushing that. They're producing FIM now!
![image](https://github.com/NOAA-OWP/hydrovis/assets/90792257/1bc2595c-f31a-4023-a94d-e3b14ec73afe)

**Comment by TylerSchrag-NOAA** [comment]
Nice job, Shawn!

**Comment by cfitzpat479** [comment]
Hey Shawn, could you check on CRNW1 as well? Getting reports from the shift that RFC FIM is not drawing just downstream of the gauge location. However, RFC FIM is drawing on a tributary that feeds into the mainstem Snoqualmie River south of Carnation, WA. Screenshots of the potential issue and the attribute table below. 
![crnw1_error](https://github.com/NOAA-OWP/hydrovis/assets/49403615/6bce2560-96da-480e-bbb9-492483d43747)
![crnw1_error2](https://github.com/NOAA-OWP/hydrovis/assets/49403615/0247f39e-4f67-4650-9b5c-6b37f8e0bf12)

**Comment by shawncrawley** [comment]
Ah, there is still an underlying shortcoming with RnR that needs to be addressed. Basically we decide where to execute Replace and Route based on wherever there are stage or streamflow forecasts that exceed action or greater, right? We can only use stage forecasts that have a rating curve since RnR models flow. Well, it turns out that on the Viz side we are ONLY using flow thresholds to analyze RnR outputs - and it looks like in some cases (notably CRNW1), the native forecast and its thresholds are in stage, and there IS a rating curve, but there are no official flow thresholds. So on the VIZ side, we are taking the output flows at the location and trying to decide if we should produce FIM there (i.e. checking if the status exceeds action), but we are not able to do that because there are no flow thresholds. Thus they are coming through Viz in the "other routing" sublayer and subsequently not being mapped with FIM due to "All flow thresholds are undefined"

So the fix would be to convert the max value at any AHPS location NWM reach back to stage using the rating curve (if it exists) and compare that stage value against the stage thresholds (if those also exist).
