### ISSUE TITLE
WPOD management has requested select gauges be filtered back into the RFC trend service that were previously excluded

### ISSUE THREAD

**Issue by cfitzpat479** [NOAA-OWP/hydrovis#611]
Please remove the following AHPS gauges from the restricted sites list so that they appear in the RFC trend service:

MCGA1
OBLA1
CIKA1
BYSA1
EFRA1
WFRA1
BLBA1

*with the caveat that management may ask for these gauges to again be filtered out in the future

**Comment by shawncrawley** [comment]
On this now. This update is purely database-centric and requires no code updates nor redeploys. I will make the changes in-place across TI, UAT and Production. Zero downtime is expected. Ready.... Go!

**Comment by shawncrawley** [comment]
Done!
