### ISSUE TITLE
Work with Alex Totten to make autoscaling more efficient for ArcGIS

### ISSUE THREAD

**Issue by MichaelFriedenthal-NOAA** [NOAA-OWP/hydrovis#617]
There was an outage on Tuesday, 1/09/24 resulting from the ArcGIS instances not autoscaling.  Once launched, it needed to patch for over an hour (ArcGIS Patches) before serving traffic, deeming it ineffective.  To prevent this from happening again, please work with Alex, to make this more efficient.  

Some options include:

1.  Setup a new image that is patched and added to the auto scaling group via image builder on a regular occurrence.

2.  Evaluate if a Warm Pool in an auto scaling group makes sense.  

3.  Any other optimizations to prevent this from happening again.

**Comment by DrixTabligan-NOAA** [comment]
The following tasks have been created:

1. Update TF scripts to include patching
2. Generate new build from applied TF updates
3. Run an instance to test newly built image and see if it still needs to be patched further.
4. If patching is still required, incorporate the additional changes in the TF scripts and re-apply and rebuild image.
5. Test built image in Dev Hydrovis 
6. _Automation tasks to follow_
7. .

Additional Tasks Github repo related:

1. Cleanout and parameterize internally all TF vars for internal storage.
2. Create subfolder in https://github.com/NOAA-OWP/hydrovis/tree/ti/Core/ImageBuilder/Pipelines for the TF image-builder deploy.
3. Do a PR to incorporate into main repository.
