### ISSUE TITLE
Archive case for WFO ILN

### ISSUE THREAD

**Issue by derekgiardino** [NOAA-OWP/hydrovis#639]
WFO ILN (Wilmington Ohio) has requested an event last year and it got pushed to this year so moving this up in priority for this year.  Their request is as follows: 
1) AnA FIM
2) RFC FIM
3) NWM FIM
4) High flow magnitude for NWM
5) Peak streamflow for RFC forecasts
6) AnA Streamflow stats
7) RFC Max Stage Forecast
8) FEMA Building Footprints for the FIM layers requested.

Time steps  
03/20/20 - 12z
03/20/20 - 18z
03/21/20 - 00z (really only needed for 1 gage, so if 4 time steps too much, this step can be sacrificed)
03/21/20 - 06z

This is more indepth in terms of HydroVIS services and would be good to show @EdisonOrellana-NOAA as a secondary historical event tracker.   

- [ ] Determine and extract all flow files are available or generated for this event
- [ ] Generate FIM gpkg for 12Z time (@shawncrawley showing @EdisonOrellana-NOAA @derekgiardino)
- [ ] Generate FIM gpkg for 18Z time (@EdisonOrellana-NOAA with @shawncrawley assistance)
- [ ] Generate FIM gpkg for 06Z time (@derekgiardino with @shawncrawley assistance)
- [ ] Pass gpkg along to ILN and OHRFC with instruction on how to add to office AGOL Account (@derekgiardino)

**Comment by shawncrawley** [comment]
@derekgiardino What is the spatial domain of this request? You mention only really needing it for one site. What site is that?
