### ISSUE TITLE
Coastal inundation maps not aligning with basemaps

### ISSUE THREAD

**Issue by frsalas-noaa** [NOAA-OWP/hydrovis#648]
See attachments as examples. The coastal inundation extents appear to be offset from the channels in the basemap in some locations. Is this a coastal model mesh issue, a FIM interpolation issue or perhaps a projection issue? Please investigate. If this is a coastal model mesh issue that we can't fix then we'll want to document this as part of the training we give to the field offices as this could mapping issue could lead to confusion.

![Image](https://github.com/NOAA-OWP/hydrovis/assets/62669859/4c2720b1-0156-41b9-9f16-163e09aebc23)

![Image](https://github.com/NOAA-OWP/hydrovis/assets/62669859/0bb39d30-f0e4-4690-94b7-037812f308b8)

**Comment by derekgiardino** [comment]
Edison, this task has come back up but I may add Shawn to it to help look into

**Comment by EdisonOrellana-NOAA** [comment]
@shawncrawley When you get back can we chat about this? Happy to take the reigns on fixing but I will need to ask you some background info-gathering questions.

**Comment by shawncrawley** [comment]
@EdisonOrellana-NOAA I'm back and am wide open meeting-wise today. Happy to chat.

**Comment by EdisonOrellana-NOAA** [comment]
@frsalas-noaa 

1. What platform is this being viewed on? NWS GIS Viewer? Other?
2. The screenshots appear to be Maine, has this only been noticed in Maine or other northerly coasts?
3. What exactly is misaligned from the screenshots? It is not entirely obvious to me what is misaligned and how it _should_ look.
4. Does the misalignment appear with every basemap? Is there a way to swap out the basemap in the viewer you were using?
5. For this issue and my own understanding, what is coastal model mesh and FIM interpolation?

**Comment by EdisonOrellana-NOAA** [comment]
@derekgiardino 
I checked against _mrf_nbm_max_inundation_5day_public.gpkg_ in 2024 Archive FIM requests > 20240922 > 1800 and found it to look okay.

I checked Texas and northerly NY to rule out Shawn's hunch on northerly grid issues. Screenshots:
![aligned](https://github.com/user-attachments/assets/a9379033-beef-4fbd-89db-65c6e8923438)
![aligned-2](https://github.com/user-attachments/assets/3c5104c6-2575-4b71-9620-8dd3c7ffd353)

If the above gpkg was not the correct one to check, let me know and I'll reopen and investigate.
