### ISSUE TITLE
Alaska - SRF Peak Flow Service: change sublayer name from 18-Hour to 15-Hour

### ISSUE THREAD

**Issue by MonicaStone-NOAA** [NOAA-OWP/hydrovis#660]
In the NWM 15-Hour Peak Flow Arrival Time Forecast - Alaska service on UAT, the sublayer name says "18-Hour Peak Flow Arrival Time", but should say "15-Hour Peak Flow Arrival Time".  This should be corrected before this service goes to Production.

**Comment by KatherinePowell-NOAA** [comment]
Checked all of the environments - TI, UAT, and Prod, and the sublayer name is correct in all. NO changes needed. Closing this issue.
