### ISSUE TITLE
Review HydroVIS SecurityHub NIST 800-53 Findings - Production

### ISSUE THREAD

**Issue by DiwakarPuthalapat-NOAA** [NOAA-OWP/hydrovis#668]
Review HydroVIS SecurityHub NIST 800-53 Findings - Production

**Comment by DiwakarPuthalapat-NOAA** [comment]
This is a ongoing task. Will Ton and I are reviewing the Security H/ub noncompliance findings weekly.

**Comment by WillTon-NOAA** [comment]
Resolved this and sent to ISSO FIPS-200 matrix to tailor out 30 controls that are not applicable to make a permanent dent to the AWS Security Hub NIST SP 800-53 Revision 5 score: https://github.com/NOAA-OWP/hydrovis-private-tasks/issues/89
