### ISSUE TITLE
HOT FIX: Streamflow AEPs CONUS: Change HWT for Clusters 1,7 and 9, reset zero HWT to minimum

### ISSUE THREAD

**Issue by KatherinePowell-NOAA** [NOAA-OWP/hydrovis#711]

**Comment by KatherinePowell-NOAA** [comment]
Made these Database changes in the TI environment:

# STEP 1: change the derived.huc8_rf_threshold table for clusters 7 & 9:

UPDATE derived.huc8_rf_thresholds
SET bankfull_rf = 'rf_2_5'
WHERE huc8_rf_thresholds.cluster = 7

UPDATE derived.huc8_rf_thresholds
SET bankfull_rf = 'rf_1_0'
WHERE huc8_rf_thresholds.cluster = 9

# STEP 2: make a backup copy of the derived.recurrence_flows_conus table

SELECT *
INTO derived.recurrence_flows_conus_backup
FROM derived.recurrence_flows_conus

# STEP 3: Add the runnoff cluster field into a new "dev" copy of the table

SELECT thresholds.*,
    clusters.cluster
INTO dev.recurrence_flows_conus
FROM derived.recurrence_flows_conus as thresholds
LEFT JOIN derived.featureid_huc_crosswalk as huc_xwalk ON huc_xwalk.feature_id = thresholds.feature_id
LEFT JOIN derived.huc8_rf_thresholds as clusters ON clusters.huc8 = huc_xwalk.huc8

# STEP 4: change the high_water_threshold values for all reaches of cluster 7 (from 3.2 to 2.5)

UPDATE dev.recurrence_flows_conus
SET high_water_threshold = rf_2_5
WHERE cluster = 7

# STEP 5: change the high_water_threshold values for all reaches of cluster 9 (from 1.1 to 1.0)

UPDATE dev.recurrence_flows_conus
SET high_water_threshold = rf_1_0
WHERE cluster = 9

# STEP 6: change all remaining zero high_water_threshold values to 0.35

UPDATE dev.recurrence_flows_conus
SET high_water_threshold = 0.35
WHERE high_water_threshold = 0

# STEP 7: copy the dev version of the recurrence_flows_conus table to the derived schema

DROP table derived.recurrence_flows_conus;
SELECT * 
INTO derived.recurrence_flows_conus
FROM dev.recurrence_flows_conus

Shawn will make the changes in UAT.

**Comment by shawncrawley** [comment]
These changes have been made to UAT. I tweaked the SQL slightly. Here is the exact SQL that I executed:

```sql
DROP TABLE IF EXISTS derived.recurrence_flows_conus_ondeck;

UPDATE derived.huc8_rf_thresholds
SET bankfull_rf = 'rf_2_5'
WHERE huc8_rf_thresholds.cluster = 7;

UPDATE derived.huc8_rf_thresholds
SET bankfull_rf = 'rf_1_0'
WHERE huc8_rf_thresholds.cluster = 9;

SELECT 
    thresholds.*,
    clusters.cluster
INTO derived.recurrence_flows_conus_ondeck
FROM derived.recurrence_flows_conus as thresholds
LEFT JOIN derived.featureid_huc_crosswalk as huc_xwalk ON huc_xwalk.feature_id = thresholds.feature_id
LEFT JOIN derived.huc8_rf_thresholds as clusters ON clusters.huc8 = huc_xwalk.huc8;


UPDATE derived.recurrence_flows_conus_ondeck
SET high_water_threshold = rf_2_5
WHERE cluster = 7;

UPDATE derived.recurrence_flows_conus_ondeck
SET high_water_threshold = rf_1_0
WHERE cluster = 9;

UPDATE derived.recurrence_flows_conus_ondeck
SET high_water_threshold = 0.35
WHERE high_water_threshold = 0;

ALTER TABLE derived.recurrence_flows_conus RENAME TO recurrence_flows_conus_backup;

ALTER TABLE derived.recurrence_flows_conus_ondeck RENAME TO recurrence_flows_conus;
```

This left a `derived.recurrnece_flows_conus_backup` table in place that can be reverted to in case of any issues.

**Comment by KatherinePowell-NOAA** [comment]
Feedback from the field so far: only negative was WA state cluster; HWT still too high. I will deploy a new RI for cluster 1 (from 2.9 to 2.2) to the TI environment and do some comparisons with the results in HFM and inundation services with UAT for that area.

**Comment by KatherinePowell-NOAA** [comment]
Deployed to the TI Database on May 10, 2024:

# Change the HUC Cluster Threshold Table
UPDATE derived.huc8_rf_thresholds
SET bankfull_rf = 'rf_2_2'
WHERE huc8_rf_thresholds.cluster = 1;

# Make a backup of the recurrence flows table
SELECT *
INTO derived.recurrence_flows_conus_backup_2
FROM derived.recurrence_flows_conus

# Make the HWT changes directly to the recurrence flows table
UPDATE derived.recurrence_flows_conus
SET high_water_threshold = rf_2_2
WHERE cluster = 1;

**Comment by shawncrawley** [comment]
The updates have been deployed to UAT.
