### ISSUE TITLE
[MEDIUM SECURITY ISSUE] IAM customer managed policies should not allow decryption actions on all KMS keys

### ISSUE THREAD

**Issue by BillFarrellNOAA** [NOAA-OWP/hydrovis#727]
[KMS.1] Checks whether the default version of IAM customer managed policies allow principals to use the AWS Key Management Service (KMS) decryption actions on all resources. This control fails if kms:Decrypt or kms:ReEncryptFrom actions are allowed on all KMS keys. The control evaluates both attached and unattached customer managed policies. It does not check inline policies or AWS managed policies.
Remediation https://docs.aws.amazon.com/securityhub/latest/userguide/kms-controls.html#kms-1

In account 526904826677,   IAM Policies HEFS, hv-vpp-ti-us-east-1-ssm, hydrovis-sys-StorageAdmin, svc-EC2-ImageSTIG-builder,

SSMInstanceProfileS3Policy,custom_policy, hydrovis-developer-CF-access.

In account 799732994462 IAM Policies HydrovisESRISSMDeploy, hv-vpp-uat-us-east-1-ssm, hv-vpp-uat-us-east-2-ssm (in both us-east-1 and us-east-2)

In account 734632823696 IAM policies hv-p-DataServicesAdmin,  hv-vpp-prod-us-east-1-ssm, hv-vpp-prod-us-east-2-ssm (in both us-east-1 and us-east-2)

**Comment by DiwakarPuthalapat-NOAA** [comment]
Suppressed the findings
