### ISSUE TITLE
[MEDIUM SECURITY ISSUE] AWS KMS key rotation should be enabled

### ISSUE THREAD

**Issue by BillFarrellNOAA** [NOAA-OWP/hydrovis#730]
[KMS.4] This AWS control checks that key rotation is enabled for each AWS KMS key. It does not check KMS keys that have imported key material. 
Remediation - https://docs.aws.amazon.com/securityhub/latest/userguide/kms-controls.html#kms-4

**AWS Account #526904826677 (Dev)**

1. 53af53c7-4366-4fe4-935e-0e536dc72aca
2. 016fb1ef-34a9-4024-b049-ed490b6f1e15
3. 1c3a7193-5e2c-4a48-ac22-021faf765cb5
4. 29c5f166-d76a-4dd3-9958-733835e09ec1
5. 43f7e965-599a-41d7-8e11-254d833f9104

**AWS Account #799732994462 (UAT)**

1. ddde3455-26e6-4ac8-8d8d-b7a46a7b4d4d
2. 6ca01eef-9a45-4e44-9c31-654d74955ee4

**AWS Account #734632823696 (Prod)**

1. cf656a69-357d-4a91-8984-42052f299f08
2. 12d45d59-fcdb-4615-be01-82325c13994c

**Comment by DiwakarPuthalapat-NOAA** [comment]
Nick to review and update terraform code

**Comment by WillTon-NOAA** [comment]
@nickchadwick-noaa  I've updated this to be the most recent KMS.4 findings as of 5/30/24, and bolded and organized them coherently based on AWS account IDs

**Comment by nickchadwick-noaa** [comment]
All KMS Keys related to our 3 accounts now have key rotation enabled.
