### ISSUE TITLE
[MEDIUM SECURITY ISSUE] API Gateway REST and WebSocket API execution logging should be enabled

### ISSUE THREAD

**Issue by BillFarrellNOAA** [NOAA-OWP/hydrovis#743]
[APIGateway.1] This control checks whether all stages of an Amazon API Gateway REST or WebSocket API have logging enabled. The control fails if the 'loggingLevel' isn't 'ERROR' or 'INFO' for all stages of the API. Unless you provide custom parameter values to indicate that a specific log type should be enabled, Security Hub produces a passed finding if the logging level is either 'ERROR' or 'INFO'.
Remediation - https://docs.aws.amazon.com/securityhub/latest/userguide/apigateway-controls.html#apigateway-1

In account 526904826677, AWSAPIGatewayStage test

In account 799732994462, AWSAPIGatewayStage prod

**Comment by DiwakarPuthalapat-NOAA** [comment]
Test API gateway deleted
