### ISSUE TITLE
[MEDIUM SECURITY ISSUE] API Gateway should be associated with a WAF Web ACL

### ISSUE THREAD

**Issue by BillFarrellNOAA** [NOAA-OWP/hydrovis#744]
[APIGateway.4] This control checks to see if an API Gateway stage is using an AWS WAF Web ACL. This control fails if an AWS WAF Web ACL is not attached to a REST API Gateway stage

Remediation - https://docs.aws.amazon.com/securityhub/latest/userguide/apigateway-controls.html#apigateway-4

In account 526904826677, AWSAPIGatewayStage test

In account 799732994462, AWSAPIGatewayStage prod

**Comment by DiwakarPuthalapat-NOAA** [comment]
API Gateway deleted
