### ISSUE TITLE
Create SD GP Service: Add terraform code that copies .mapx files to S3

### ISSUE THREAD

**Issue by shawncrawley** [NOAA-OWP/hydrovis#782]
Terraform file to edit: https://github.com/NOAA-OWP/hydrovis/blob/ti/Core/LAMBDA/viz_functions/main.tf
Example terraform code: https://stackoverflow.com/a/58827910

**Comment by EdisonOrellana-NOAA** [comment]
[This reference](https://github.com/NOAA-OWP/hydrovis/blob/08d4a247b92e6a85e36228946ead85ec5d37b4a1/Core/LAMBDA/viz_functions/main.tf#L905C1-L928C2) can be used to create similar tf to upload mapx to proper location on s3.

**Comment by EdisonOrellana-NOAA** [comment]
Completed with commit: 3163867690e4b6dd377f9371bc0866f39a538782
