### ISSUE TITLE
We will need to change permissions to PR VI SRF High Flow Magnitude to Public

### ISSUE THREAD

**Issue by derekgiardino** [NOAA-OWP/hydrovis#809]
Pretty basic, just a reminder that we will need to change the PR VI SRF High Flow Magnitude to public and drop the _noaa from the service name so it will be public and available to NWPS.  In the meantime, I can just point them to the UAT version for their testing.

**Comment by shawncrawley** [comment]
This already exists as described, I'm going to close this.
