### ISSUE TITLE
Port over HAND FIM 4.5.2.11 to HydroVIS

### ISSUE THREAD

**Issue by derekgiardino** [NOAA-OWP/hydrovis#813]
Major FIM Hand / ras2fim data loads for new FIM releases

All of this is based on new FIM data for loading and/or processing
- Crosswalk files  - done Aug 6, 2024
- Create AEP Pipeline data  - rebuild completed Aug 23
- Catchment data - rebuild done Aug 22
- usgs_elev_tables - done
- hydrotables - done
- usgs_rating_curve - done
- Skills metrics data - done
- FIM Performance - WIP (waiting for fim_performance_catchments)
- CatFIM - Stage-Based - data still coming
- CatFIM - Flow-Based - done and loaded in TI
- CatFiM - FIM 30 - see card [858](https://github.com/NOAA-OWP/hydrovis/issues/858)
- ras2fim - done

**Comment by RobHanna-NOAA** [comment]
I believe all of the load scripts into TI are done and succesful. The last are being loaded into UAT now. New tickets will be created if more issues arise
