### ISSUE TITLE
Add new "model_version" field to all inundation services/sublayers

### ISSUE THREAD

**Issue by shawncrawley** [NOAA-OWP/hydrovis#824]
With FIMv5.0 (i.e. HAND 4.5.2.11 and ras2fim 2.0.0), we're adding a new "model_version" field so we can differentiate between the public fim version - which will remain as the "fim_version" field, but now reflect "v5.0.0" (three segments) and the version of the model that produced the FIM (whether HAND or RAS2FIM).

This will involve the following:

- [ ] Add `model_version` alongside fim_version in all SQL queries that use `fim_version`
- [ ] Verify if `model_version` needs to be added/hard-coded in any Python files - namely the `viz_fim_data_prep` and `hand_fim_processing` Lambdas
- [ ] Add `model_version` to all "sqlQuery" statements in all `.mapx` files that use `fim_version`
- [ ] Add a `{"name" : "model_version", "type" : "esriFieldTypeString", "alias": "model_version", "length": 20}` entry to the "queryFields" section of all sublayers in all `.mapx` files that use `fim_version`
- [ ] Add a `{"type" : "CIMFieldDescription", "alias" : "Model Version", "fieldName" : "model_version", "visible" : true, "searchMode" : "Exact"}` entry to the "featureTable" -> "fieldDescriptions" section of all sublayers in all `.mapx` files that use `fim_version`

**Comment by EdisonOrellana-NOAA** [comment]
As mentioned, putting here for documentation/investigation. Proposal to track model version in table meta data. Data is SELECTable. The comments at this link also mention putting any arbitrary JSON in there. Go wild
[Adding metadata to table in Postgres](https://stackoverflow.com/questions/17947274/is-it-possible-to-add-table-metadata-in-postgresql)

**Comment by RobHanna-NOAA** [comment]
Believed to be all done and checked in. More testing required, but looks good. Closing item
