### ISSUE TITLE
Urgent: Missing inundation 

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/hydrovis#889]
Details not yet confirmed but appears to have been seen in Prod forecast views?

(from email Sep 19)
(Matt)
Carson has pointed out some areas that appear to be missing inundation in branch 2582000038 (HUC 08020302). I've compared this with inundation from v4.5.2.11 using the RFC flows. The affected HydroIDs are 18280178, 18280187, and 18280188.

For reference, you can compare the image below with the screenshot that Carson took at the bottom.

![image](https://github.com/user-attachments/assets/fc1031f3-52ed-44f6-ac09-f21b9e4d4452)

If could document these HydroIDs along with the HUC/Branch in an email and send to Derek, Shawn, and Rob, that would be great. They may ask us to submit a VLAB ticket, but since has the potential to be a bigger issue, they may let us get away with an email.

![image](https://github.com/user-attachments/assets/e1a3983a-c37b-47fa-8cce-16194d33dab1)

Derek:
To clarify, these maps are generated in your dev environment but when published on HydroVIS they seem to be missing for the mentioned Hydro IDs? 

Matt:
Yeah, exactly. The map with the red circles is the one I made and the other map is a screenshot that Carson took based on Hydrovis.

**Comment by mluck** [comment]
Additionally, these areas circled in red appear to be missing inundation in Hydrovis (see bottom image)
![image](https://github.com/user-attachments/assets/21bc7eec-bf6c-43ca-845c-4731d4ce0ad7)

![image](https://github.com/user-attachments/assets/aff3d293-b75e-484e-8532-56387f1ac480)

**Comment by CarsonPruitt-NOAA** [comment]
Not sure if you guys have done anything to fix this, but this area seems much better today with no gaps like there were last week.

**Comment by CarsonPruitt-NOAA** [comment]
![image](https://github.com/user-attachments/assets/81779f56-383e-4d24-94ba-754d16179339)
