### ISSUE TITLE
Fix HAND FIM issue when rating curve does not exist or yields NaN

### ISSUE THREAD

**Issue by shawncrawley** [NOAA-OWP/hydrovis#950]
This issue was discovered in Prod and reported in VLab: https://vlab.noaa.gov/redmine/issues/136201. At the time, we got the go-ahead from @derekgiardino to do a manual, in-place hotfix as a band-aid. While that worked, an official fix either needs to be pushed through in our next release or officially hotfixed via code and deployment to prevent the temp fix from being overwritten.

**Comment by RobHanna-NOAA** [comment]
This could be a FIM issue. We created a card to look into it, Number [1339](https://github.com/NOAA-OWP/inundation-mapping/issues/1339). If it is a fix in FIM, or at least some explanation is found, we need to update our HV code to put in a message of why this happens, or remove that hardcoded exception when a new release comes out.

**Comment by RobHanna-NOAA** [comment]
![image](https://github.com/user-attachments/assets/26497a4a-50fb-4370-aa9b-28a49dc539a3)
