### ISSUE TITLE
Intro to hydrovis

### ISSUE THREAD

**Issue by EdisonOrellana-NOAA** [NOAA-OWP/hydrovis#979]
Show some ins and outs of hydrovis for Lorne

**Comment by EdisonOrellana-NOAA** [comment]
- [x] Provide overview documents to Lorne

**Comment by EdisonOrellana-NOAA** [comment]
- [x] Create NOAA Github acct
- [x] Gain access to VLAB repos and get added to necessary groups and projects
- [x] AWS access for ti and r/o prod
- [x] Development EC2 instance

**Comment by LorneLeonard-NOAA** [comment]
Checking my github account access.
